config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/createBlog'
  get 'home/loginPage'

  post 'login', to: 'home#login'
  post 'add_Item' , to: 'home#add_Item'
  get 'view_list' , to: 'home#view_list'
  get 'delete_data/:id' , to: 'home#delete_data'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    flash[:alert] = 'User not found.'
    render 'home/createBlog'
  end

  def login
    @em = params[:address]
    @pw = params[:password]
    puts @em,@pw
    puts 'nizar----------------------------------'
    @email = User.all

    @email.each do |f|
      puts f.email
    end

    @user = User.find_by_email(params[:address])
    if @user
      puts 'got it'
    end

    if @user && @user.valid_password?(params[:password])
      puts 'clear'
      render 'createBlog'
    else
      render 'loginPage'
      flash[:alert] = 'User not found.'
      puts 'not'
    end
  end

  def add_Item
    @bike = Bike.new(primary_key: params[:bikeId], name: params[:name], rent: params[:price])
    @bike.save
    render 'createBlog'
  end

  def view_list
    @bikes = Bike.all
    render 'view_list'
  end

  def delete_data
    Bike.destroy(params[:id])
    render "view_list"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navBar">
<div class="nav-wrapper ">
  <a href="#" class="brand-logo">Royal Blog</a>
  <ul id="nav-mobile" class="right hide-on-med-and-down">
  <% if !(user_signed_in?) %>
  <li class="nav-item">
  <%= link_to "Sign in" , home_loginPage_path , class:" nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Sign up" , new_user_registration_path , class:" nav-link" %>
  </li>

<% else %>
  
   <li class="nav-item">
   <%= link_to "Sign out" , destroy_user_session_path , method: :delete, class:"nav-link" %>
  </li>
  <li class="nav-item">   
   <%= link_to "Create your Blog" , home_createBlog_path , class:"btn btn-danger" %>
  </li>
  <li class="nav-item">
    <%= link_to "Profile" , edit_user_registration_path , class:" nav-link" %>
   </li>
 </li>
<li>
<a href="#" ></a>
</li>


<% end %>
  </ul>
</div>
</nav>

app/views/home/authentication/signupPage.html.erb
<div class="userRegistrationForms">
 <h1>Login

app/views/home/createBlog.html.erb
  <div class="section loginForm"></div>
  <main>
    <center>
      <div class="container">
      <div class="section"></div>

      <h5 class="indigo-text">Add Product Details,</h5>
      <div class="section"></div>
        <div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

          <%= form_with url: "/add_Item", class:" col s12" , method: :post do |f| %>
            <div class='row'>
              <div class='col s12'>
              </div>
            </div>

            <div class='row'>
              <div class='input-field col s12'>  
                <%= f.number_field :bikeId, size: "70x5" %>
                <%= f.label :bikeId, "Key" %>
              </div>
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                <%= f.text_field :name , class:"input-field col s12"  %>
                <%= f.label :name, "Name" %>
              </div>
            </div>
            <div class='row'>
              <div class='input-field col s12'>  
                <%= f.number_field :price, size: "70x5" %>
                <%= f.label :price, "Price" %>
              </div>
            </div>

            <br />
            <center>
              <div class='row'>
                <%= f.submit "Submit" , class: "col s12 btn btn-large waves-effect indigo"  %>
              </div>
            </center>
          <% end %>
        </div>
      </div>
      <a><%= link_to "View List" , view_list_path , class:" nav-link" %></a>
    <div class="section"></div>
    <div class="section"></div>
  </main>

app/views/home/index.html.erb
<% if !(user_signed_in?) %>
<%= link_to "Create your blog", home_createBlog_path, class: 'btn btn-danger' %>
<% end %>

app/views/home/loginPage.html.erb
  <div class="section loginForm"></div>
  <main>
    <center>
      <div class="container">
      <div class="section"></div>

      <h5 class="indigo-text">Please, login into your account</h5>
      <div class="section"></div>
        <div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

          <%= form_with url: "/login", class:" col s12" , method: :post do |f| %>
            <div class='row'>
              <div class='col s12'>
              </div>
            </div>

            <div class='row'>
              <div class='input-field col s12'>  
                <%= f.email_field :address , class:"input-field col s12" %>
                <%= f.label :address, "e-mail" %>
              </div>
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                <%= f.password_field :password , class:"input-field col s12"  %>
                <%= f.label :password, "Password" %>
              </div>
              <label style='float: right;'>
								<a class='pink-text' href='#!'><b>Forgot Password?</b></a>
							</label>
            </div>

            <br />
            <center>
              <div class='row'>
                <%= f.submit "Submit" , class: "col s12 btn btn-large waves-effect indigo"  %>
              </div>
            </center>
          <% end %>
        </div>
      </div>
      <a href="#!">Create account</a>
    <div class="section"></div>
    <div class="section"></div>
  </main>

app/views/home/view_list.html.erb
<table class="table table-striped">
  <tr>
    <th>key</th>
    <th>Id</th>
    <th>Name</th>
    <th>Rent</th>
  </tr>
   <% @bikes.each do |b| %>
   <td><%= b.primary_key %> </td>
   <td><%= b.id %> </td>
   <td><%= b.name %> </td>
   <td><%= b.rent %> </td>
   <td><%= link_to "delete" delete_data_path (b.id), :class=>"inbox-sf-add-btn tip" %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoyalBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
            
   <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
  
  </head>

  <body>
  <%= render "home/navbar" %>
  <div class= "position-absolute top-50 start-50 translate-middle">
    <%= yield %>
  <div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>